Feat/age5 modifications
morpho-dao/morpho-rewards pull request #106
Opened 2023-05-17 08:43 UTC by julien-devatom

### Description of change
- Add ma3 ETH marked
- Add `age5` emission script following the vote proposal

Closes: #105 

### Pull-Request Checklist

- [ ] Code is up-to-date with the `main` branch
- [ ] `yarn lint` passes with this change
- [ ] `yarn test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2023-05-17 10:08 UTC, MerlinEgalite reviewed
LGTM but one question

2023-05-17 10:08 UTC, MerlinEgalite commented on README.md
> +nvm use
```suggestion
nvm use 18
```

no?

2023-05-17 10:08 UTC, MerlinEgalite commented on src/ages/distributions/ageFiveDistribution/marketsRepartition.ts
> +    market: "0x030bA81f1c18d280636F32af80b9AAd02Cf0854e",
ma3 workds with underlying addresses, is this still ok?

2023-05-17 10:18 UTC, julien-devatom commented on README.md
> +nvm use
it fallback on the `.nvmrc` by default

2023-05-17 13:13 UTC, oumar-fall requested changes

2023-05-17 13:13 UTC, oumar-fall commented on src/utils/markets/fetchMarketsData.ts
> +      const aToken = AToken__factory.connect(underlying, provider);
⚠️ underlying !== aToken

2023-05-17 13:13 UTC, oumar-fall commented on src/utils/markets/fetchMarketsData.ts
> +      const { variableDebtTokenAddress } = await lendingPool.getReserveData(underlying, overrides);
you should get the aToken address here as well

2023-05-17 13:13 UTC, oumar-fall commented on src/utils/markets/fetchMarketsData.ts
> +        oracle.getAssetPrice(underlying, overrides).then((price) => price.mul(10 ** 10)), // from 8 to 18 decimals
on aaveV2 price are given with 18 decimals no?

2023-05-17 13:13 UTC, oumar-fall commented on src/utils/markets/fetchMarketsData.ts
> +        oracle.getAssetPrice(underlying, overrides),
and here it's with 8 decimals

2023-05-17 13:36 UTC, julien-devatom commented on src/utils/markets/fetchMarketsData.ts
> +      const aToken = AToken__factory.connect(underlying, provider);
fixed

2023-05-17 13:44 UTC, oumar-fall approved these changes

2023-05-19 08:38 UTC, ghivert approved these changes

2023-05-20 11:11 UTC, merged