Feat/age7 configuration
morpho-dao/morpho-rewards pull request #124
Opened 2023-08-15 11:33 UTC by julien-devatom

### Description of change
- Following this [MIP](https://forum.morpho.org/t/mip-morpho-rewards-age-7/348)
- If the vote is not massing, we'll remove the age7 configuration from the main branch.

### Pull-Request Checklist

- [ ] Code is up-to-date with the `main` branch
- [ ] `yarn lint` passes with this change
- [ ] `yarn test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2023-08-15 12:05 UTC, oumar-fall commented on src/age-epochs.json
> +          "sizeDistribution": {
```suggestion
          "sideDistribution": {
```

2023-08-15 12:05 UTC, oumar-fall commented on src/age-epochs.json
> +              "supplySize": 5000,
```suggestion
              "supplySide": 5000,
```

2023-08-16 07:52 UTC, oumar-fall approved these changes

2023-08-16 07:53 UTC, oumar-fall commented
I didn't check the values though

2023-08-16 08:13 UTC, mlgarchery approved these changes

2023-08-16 08:22 UTC, mlgarchery commented on src/age-epochs.json
> +          "symbol": "aWETHV3",
it's aWETHv3 or aWETHV3 ?

2023-08-16 08:29 UTC, ghivert requested changes
I really think the type should be refined and expanded in the future. Otherwise everything's fine, and the values are correct according to the MIP.

2023-08-16 08:29 UTC, ghivert commented on src/ages/distributionScripts/simpleVoteDistribution.ts
>      type: string;
Isn't it a union here ? `type: 'static'` ?

2023-08-16 12:05 UTC, ghivert approved these changes

2023-08-16 12:08 UTC, merged