:bug: Fix getUserBalances by using standard fetch instead of axios
morpho-dao/morpho-rewards pull request #52
Opened 2022-12-29 18:03 UTC by ghivert

### Description of change

An outdated version of `axios` was causing an `unexpected end of file` bug. Switching to `fetch` is enough to make the bug go away.
It's now working on Node 18 and more only.

### Pull-Request Checklist

- [x] Code is up-to-date with the `main` branch
- [x] `yarn lint` passes with this change
- [ ] `yarn test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2022-12-30 14:19 UTC, Rubilmax reviewed
We could require node `>=18` in `package.json`, considering that nodejs v18 is widely available?

2022-12-30 16:39 UTC, ghivert commented
We talked with Julien, and it's not as straightforward as I thought, he'll check on the WE

2023-01-03 14:19 UTC, julien-devatom requested changes

2023-01-03 14:19 UTC, julien-devatom commented on src/utils/getUserRewards.ts
> +  if (!res.ok) throw Error(res.status.toString());
What if there is a non 200 resp but with more information in the body? here for a subgraph error, we have more information in `res.data.errors` for example

2023-01-04 14:06 UTC, julien-devatom approved these changes
LGTM

2023-01-04 14:06 UTC, merged